### ISSUE TITLE
Online version of MT3

### ISSUE THREAD

**Issue by AI678** [AlexanderBartler/MT3#1]
Hi, thanks for sharing your great work. In your paper, the adaptation process is done in an offline manner. That is you reset model parameters for each test image. Have you ever evaluated the online version of JT(BYOL) or MT3(BYOL) ?

**Comment by AlexanderBartler** [comment]
Hi, 
that's correct, we reset the parameters during testing after each image. We are currently investigating the online setting, should be possible with slight modifications, e.g. the learning rate during testing needs to be adapted.

**Comment by AI678** [comment]
Thank you.
